name: build-and-publish
on:
  push:
    branches: [ ef-core-net-7 ]
      
jobs:     
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build --configuration Release --no-restore

    - name: Generate package
      run: dotnet pack src/EFCoreUnitOfWork/EFCoreUnitOfWork.csproj -c Release -o out

    - name: Push to NuGet
      run: |
        cd out
        dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source ${{ secrets.NUGET_SOURCE }} --skip-duplicate
