name: ef-core-unit-of-work
on:
  push:
    branches: [ ef-core-unit-of-work-5 ]
  pull_request:
    branches: [ ef-core-unit-of-work-5 ]
      
jobs:     
  publish:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build --configuration Release --no-restore

    - name: Generate package
      run: dotnet pack EFCoreUnitOfWork.csproj -c Release -o out

    - name: Push to NuGet
      run: |
        cd out
        dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source ${{ secrets.NUGET_SOURCE }} --skip-duplicate
